name: data-lakeview
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - streamlit
  - pandas
  - altair
  - pillow
  - pyvis
  - networkx
  - pip
  - pip:
    - snowflake-snowpark-python
