"""Client application classification mappings.

Single source of truth for mapping raw client application strings to display names.
Used by both the SQL stored procedure (via lookup table) and the app's auto-setup.

Each tuple: (ilike_pattern, source_field, display_name)
  - source_field: "application" or "client_app_id"
  - Patterns are matched in order; first match wins.
"""

CLIENT_MAPPINGS = [
    # source_field: client_app_id
    ("%snowpark%", "client_app_id", "Snowpark"),
    # source_field: application
    ("%SNOWPARK%", "application", "Snowpark"),
    ("%deployments%", "application", "Kafka"),
    ("%cosmos%", "application", "COSMOS"),
    ("%rappid%", "application", "RAPPID"),
    ("%dtlk%", "application", "DTLK"),
    ("%nice%", "application", "NICE"),
    ("%nexis%", "application", "NEXIS"),
    ("%MASHUP%", "application", "Power BI"),
    ("%POWERBI%", "application", "Power BI"),
    ("%microsoftonprem%", "application", "Power BI"),
    ("%adbc%go%", "application", "ADBC-Go"),
    ("%DTS%", "application", "SSIS"),
    ("%DTEXEC%", "application", "SSIS"),
    ("%datastage%", "application", "IBM DataStage"),
    ("%REPORTSERVER%", "application", "SSRS/PBIRS"),
    ("%MSRS%", "application", "SSRS/PBIRS"),
    ("%REPORTINGSERVICE%", "application", "SSRS/PBIRS"),
    ("%REPORTBUILDER%", "application", "SSRS/PBIRS"),
    ("%VISUALSTUDIO%", "application", "SSRS/PBIRS"),
    ("%SQLSe%", "application", "SQL Server"),
    ("%GRAFANA%", "application", "Grafana"),
    ("%CIRRUS%", "application", "Cirrus CI"),
    ("%TOAD%", "application", "Toad"),
    ("%BOOTSTRAP%", "application", "Tomcat"),
    ("%QLIKREPL%", "application", "Qlik Replicate"),
    ("%rstudio%", "application", "RStudio"),
    ("%MicroStrat%", "application", "MicroStrategy"),
    ("%TABLEAU%", "application", "Tableau"),
    ("%HYPERION%", "application", "Hyperion"),
    ("%softoffice%", "application", "Microsoft Office"),
    ("%msacces%", "application", "Microsoft Access"),
    ("%DATABRICKS%", "application", "Databricks/Spark"),
    ("%dbatch%", "application", "Databricks/Spark"),
    ("%SPARK%", "application", "Databricks/Spark"),
    ("%ALTERYX%", "application", "Alteryx"),
    ("%INFA_DI%", "application", "Informatica Cloud"),
    ("%CDATA%", "application", "CData"),
    ("%fivetran%", "application", "Fivetran"),
    ("%tibco%", "application", "Tibco Spotfire"),
    ("%palantir%", "application", "Palantir"),
    ("%PERL%", "application", "Perl"),
    ("%iis%", "application", "Microsoft IIS"),
    ("%inets%", "application", "Microsoft IIS"),
    ("%w3wp%", "application", "Microsoft IIS"),
    ("%BUSINESSOBJECTS%", "application", "Business Objects"),
    ("%bobj%", "application", "Business Objects"),
    ("%DOMO%", "application", "Domo"),
    ("%astronomer%", "application", "Astronomer"),
    ("%DATAFACTORY%", "application", "Azure Data Factory"),
    ("%INTEGRATIONRUNTIME%", "application", "Azure Data Factory"),
    ("%EXCEL%", "application", "Excel"),
    ("%SNOWFLAKE%", "application", "Snowflake Web"),
    ("%JARVIS%", "application", "Jarvis"),
    ("%WEBJOBS%", "application", "Azure App Service/WebJobs"),
    ("%JENKINS%", "application", "Jenkins"),
    ("%KAFKA%", "application", "Kafka"),
    ("%airflow%", "application", "Airflow"),
    ("%starburst%", "application", "Starburst"),
    ("%prest%", "application", "Presto"),
    ("%boomi%", "application", "Boomi"),
    ("%SAS%", "application", "SAS"),
    ("%arcgis%", "application", "ArcGIS"),
    ("%dbeave%", "application", "DBeaver"),
    ("%vscode%", "application", "VSCode"),
    ("%teradata%", "application", "Teradata"),
    ("%powershell%", "application", "PowerShell"),
    ("%uipath%", "application", "UiPath"),
    ("%fads%", "application", "Fads"),
    ("%snowcli%", "application", "SnowCLI"),
    ("%intellij%", "application", "IntelliJ"),
    ("%sigma%", "application", "Sigma"),
    ("%talend%", "application", "Talend"),
    ("%thoughspot%", "application", "ThoughtSpot"),
    ("%install4j%", "application", "install4j"),
    ("%cognos%", "application", "Cognos"),
    ("%nimbus%", "application", "Nimbus"),
    ("%surefire%", "application", "Apache Maven Surefire"),
    ("%dataiku%", "application", "Dataiku"),
    ("%laserfiche%", "application", "Laserfiche"),
    ("%coalesce%", "application", "Coalesce"),
    ("%wherescape%", "application", "WhereScape"),
    ("%salesforce%", "application", "Salesforce"),
    ("%diffcheck%", "application", "Diffchecker"),
    ("%flyspeed%", "application", "FlySpeed SQL"),
    ("%AdvancedQuery%", "application", "AdvancedQueryTool"),
    ("%python%", "application", "Python"),
    # source_field: client_app_id (fallback patterns when application IS NULL)
    ("%SNOWFLAKE%", "client_app_id", "Snowflake Web"),
    ("%JDBC%", "client_app_id", "JDBC"),
    ("%javascript%", "client_app_id", "Javascript"),
]
